name = "hyperdrive"
main = "src/index.ts"
compatibility_date = "2023-11-28"

node_compat = true # required for database drivers to function

# Pasted from the output of `wrangler hyperdrive create $NAME --connection-string=[...]` above.
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "02058b3537b54835bc4a409017d918f6"